### ISSUE TITLE
Revert automatic default actions

### ISSUE THREAD

**Issue by eldoy** [eldoy/waveorb#112]
We removed it for no good reason, it can come in handy when prototyping:

https://github.com/eldoy/waveorb/commit/5ac62004926db5090e08755fe0123ed0d1d5cd98

Maybe even expand to make it even more automatic?

`config/actions.yml`:

```yml
automatic: all

# or specific
automatic: 
  - project
  - user
```

Without `automatic` they are not automatic at all. Or should they be with empty file?
