### ISSUE TITLE
Named assets

### ISSUE THREAD

**Issue by eldoy** [eldoy/waveorb#44]
Sometimes we want to bundle something in several ways. If we have this:
```yml
bundle:
  js:
    - /js/haka.js
    - /js/waveorb.js
    - /codemirror/lib/codemirror.js
    - /codemirror/addon/mode/overlay.js
    - /codemirror/mode/meta.js
    - /js/app.js
  css:
    - /css/build/app.css
    - /codemirror/lib/codemirror.css
```

then we might want to bundle code mirror separately as it is only used in the admin interface and should not be loaded on the home page.

Can we have something like this?

```yml
bundle:
  js:
    default:
      - /js/haka.js
      - /js/waveorb.js
    codemirror:
    - /codemirror/mode/htmlmixed/htmlmixed.js
    - /codemirror/mode/clike/clike.js
    - /codemirror/mode/meta.js
    - /js/app.js
  css:
    default:
      - /css/build/app.css
      - /codemirror/lib/codemirror.css
```

???
