### ISSUE TITLE
Sitemap multiple language support

### ISSUE THREAD

**Issue by eldoy** [eldoy/waveorb#71]
Right now support for multiple languages is a bit tedious since there is too much duplication.

Write a translation layer for some of the options to alleviate.

```yml
hostname: https://eldoy.com
urls:
  - url: /
    lastmodfile: app/pages/index.js
    changefreq: weekly
    priority: 1.0
    links:
      - url: /
        lang: en
      - url: /no/
        lang: 'no'
  - url: /no/
    lastmodfile: app/pages/index.js
    changefreq: weekly
    priority: 1.0
    links:
      - url: /
        lang: en
      - url: /no/
        lang: 'no'
```

Can we generate that from something like this?

```yml
hostname: https://eldoy.com
urls:
  - url: /
    lastmodfile: app/pages/index.js
    changefreq: weekly
    priority: 1.0
    links:
      - url: /
        lang: en
      - url: /no/
        lang: 'no'
```
